    <div id="footer">
        <div class="container">
                <div class="col-md-4 col-sm-4" id="newsletter">
                    <div class="row">
                        <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>
                    </div>
                </div>
                <div class="col-md-5 col-sm-5" id="social">
                    <div class="row">
                    <div>
                        <img class="logo"  src="<?php echo $this->getSkinUrl('img/logo.png'); ?>">
                    </div>
                    <div>
                        <a class="fa fa-facebook fa-social" href="https://www.facebook.com/dokonalerasy/" target="_blank"></a>
                        <a class="fa fa-instagram fa-social" href="https://www.instagram.com/violet_lashes/" target="_blank"></a>
                        <a class="fa fa-youtube-play fa-social" href="https://www.youtube.com/user/dokonalerasy" target="_blank"></a>
                    </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3" id="contact">
                    <div class="row">
                    <p>Salon <b>VIOLET Lashes<sup>&reg;</sup></b>
                    <br>Ekaterina Kimlová</p>
                    <p>tel. <span style="font-size: 22px">+420 <b>607 224 190</b></span>
                    <br>violetlashesostrava@gmail.com
                    <br>Jiráskovo náměstí 2 <b>Ostrava</b>
                    <br>IČ: 76465241</p>
                    </div>
                </div>
        </div>
    </div>
    <div id="footer1">
        <hr>
        <div class="container">
            <span class="left">Designed by <a href="http://www.creacore.cz" target="_blank">Creacore</a></span>
            <span class="right"><a href="#top" class="fa fa-chevron-up"></a> </span>
        </div>
    </div>