<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<div class="col-md-12 post">
	<?php echo $this->getBeforePostContentHtml() ?>
		<?php if ($post->isViewableForVisitor()): ?>
				<div class="row">
					<div class="col-md-4">
						<?php if ($featuredImage = $post->getFeaturedImage()): ?>
							<div class="image" style="background-image: url('<?php echo $featuredImage->getAvailableImage() ?>');" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"></div>
						<?php else: ?>
							<div class="image" style="background-image: url('http://placehold.it/345x280');" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"></div>
						<?php endif; ?>
					</div>
					<div class="col-md-8">
						<h2><?php echo $this->escapeHtml($post->getPostTitle()) ?></h2>
						<?php $content = $post->getPostContent(); $content = strip_tags($content); echo substr($content, 0, 800) . "..."; ?>
						<div style="margin-top: 15px">
							<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>" class="btn btn-primary">Celý příspěvek</a>
						</div>
					</div>
				</div>
		<?php else: ?>
			<?php echo $this->getPasswordProtectHtml($post) ?>
		<?php endif; ?>
	<?php echo $this->getAfterPostContentHtml() ?>
</div>