<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<div class="post-list-item col-md-12">
	<h2><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h2>
	<?php echo $this->getBeforePostContentHtml() ?>
	<div class="row">
		<?php if ($post->isViewableForVisitor()): ?>
			<?php if ($featuredImage = $post->getFeaturedImage()): ?>
				<div class="col-md-4">
				</div>
				<div class="col-md-8">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></a>
					<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
						<?php echo $post->getPostExcerpt() ?>
					<?php else: ?>
						<?php echo $post->getPostContent() ?>
					<?php endif; ?>
				</div>
			<?php else: ?>
				<div class="col-md-4">
					<img src="placehold.it/800x800">
				</div>
				<div class="col-md-8">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></a>
					<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
						<?php echo $post->getPostExcerpt() ?>
					<?php else: ?>
						<?php echo $post->getPostContent() ?>
					<?php endif; ?>
				</div>
			<?php endif; ?>
		<?php else: ?>
			<?php echo $this->getPasswordProtectHtml($post) ?>
		<?php endif; ?>
	</div>
	<?php echo $this->getAfterPostContentHtml() ?>
</div>