<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<div class="col-md-12">
<?php if ($post): ?>
	<?php $helper = $this->helper('wordpress') ?>
	<?php $author = $post->getAuthor() ?>
	<?php if($post ->getPostType() != "page"): ?>
	<div class="page-title post-title show-this-title-please">
		<h1><?php  echo $this->escapeHtml($post->getPostTitle()) ?></h1>
	</div>
	<?php endif; ?>
		<?php echo $this->getBeforePostContentHtml() ?>
			<?php if ($post->isViewableForVisitor()): ?>
				<?php echo $post->getPostContent() ?>
			<?php else: ?>
				<?php echo $this->getPasswordProtectHtml() ?>
			<?php endif; ?>
		<?php echo $this->getAfterPostContentHtml() ?>
		<?php echo $this->getCommentsHtml() ?>
</div>
<?php endif; ?>